### ISSUE TITLE
vintage plugin no longer working post install

### ISSUE THREAD

**Issue by cbrinley219** [kiteco/KiteSublime#10]
After installing kite sublime the vintage package no longer works (aka vi/vim style key bindings). I have verified my user settings contain an empty array for this item `ignored_packages`:
```
{
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
...
	"ignored_packages": [],
...
}
```
Is this expected behavior?

**Comment by dhung09** [comment]
Hi @cbrinley219 this should be fixed as of Kite v0.20181113.0. You may need to uninstall/reinstall the Sublime Text plugin from the Copilot for the fix to take effect.

**Comment by cbrinley219** [comment]
thanks very much! i will reinstall and test

**Comment by cbrinley219** [comment]
hmm i was just about to reinstall and i noticed i have this version of Kite: `Version: 0.20181114.1`
perhaps the issue still persists?

let me know if there is any data i can provide to give visibility into this issue.

**Comment by cbrinley219** [comment]
confirmed reinstall was required and did fix the issue. thanks! btw very much enjoying this tool so far!

**Comment by dhung09** [comment]
Great! Please let us know if you have future issues or feedback in general.
