### ISSUE TITLE
Remove signature completions in lieu of advanced completions from Kite Engine

### ISSUE THREAD

**Issue by its-dhung** [kiteco/KiteSublime#28]
See [kiteco/kiteco#6998 (comment)](https://github.com/kiteco/kiteco/issues/6998#issuecomment-463019994)

**Comment by metalogical** [comment]
Do we want to remove signature completions entirely, or merge them with kited completions?

If we remove them entirely, do we want to replicate the signature completion behavior in kited?

**Comment by its-dhung** [comment]
Fixed by #33
