### ISSUE TITLE
Hover over gutter triggers popup

### ISSUE THREAD

**Issue by pykong** [kiteco/KiteSublime#46]
KiteSublime seems to hide other popups that should appear when hovering the gutter.

In my understanding, the Kite popup should only appear when hovering over a symbol directly.
However, the gif provided shows SublimeLinter's popup briefly flashing before becoming replaced by that of Kite's. I categorize this behavior as a bug, as it appears unintended and detrimental.

![KiteGutter](https://user-images.githubusercontent.com/20211140/58385751-7d744e00-7ff5-11e9-9fde-6caeb9aa57fc.gif)
_(at the end of the animation a normal SublimeLinter popup is shown demonstrating the expected behavior)_

Versions:
Sublime Text 3: 3208
Kite engine: 2.20190423.1
KiteSublime: ? (appears up-to-date)

**Comment by its-dhung** [comment]
@jansorg do you think you can take a look at this?

**Comment by pykong** [comment]
As a side note: The issue at hand is tangent to a lacking feature of Sublime Text.
There is no precedence mechanism for gutter icons. At least no API to make the gutter icons of one plugin to prevail over those of another.
