### ISSUE TITLE
how to install kite as root?

### ISSUE THREAD

**Issue by 5l1v3r1** [kiteco/KiteSublime#64]
is there a way to install it as root?

**Comment by SofianeHamlaoui** [comment]
what do you mean by installing it as root ?

**Comment by its-dhung** [comment]
There's currently no way to install Kite as root, but the installer doesn't need root privileges.

**Comment by 5l1v3r1** [comment]
well there is a  way, changing getuid with getppid with hex editor.

**Comment by ugurilgin** [comment]
> is there a way to install it as root?

You must remove these projects . I have the license for these projects. If you do not remove the projects, I will have to take legal action.
https://github.com/5l1v3r1/BrainTumorDetection 
https://github.com/5l1v3r1/Cocuk-Takip-Sistemi 
https://github.com/5l1v3r1/Python-Goruntu-Isleme
