### ISSUE TITLE
Autocomplete skips first letter

### ISSUE THREAD

**Issue by dionisiovj** [kiteco/KiteSublime#73]
When an autocomplete option is offered and I use it (in my case hit tab), the first letter will be skipped e.g. None -> one, class -> lass, return -> eturn, etc. It doesn't happen always but right now it does happen 90% of the time.

I started noting this behaviour today. Last time I used the plugin one month ago (February/March) I didn't notice this.

Here some information about my system:

Sublime Text Build 3211
OS: Ubuntu 18.04
Anaconda IDE installed but configured as recommended by kite (disable autocompletions and signature display)

**Comment by its-dhung** [comment]
Could you please share a couple of things to help us debug:

1. What other packages have you installed for Sublime?
2. If you can reliably reproduce this issue, change Kite's `verbose_logs` setting to `true`, reproduce the issue, and then report what you see in Sublime's console. You can access Kite's settings via the command `Kite: Package Settings`.
3. Can you share a piece of example code that allows you to reproduce this issue?

Thanks for your help!

**Comment by dionisiovj** [comment]
I've stopped seeing this behaviour. Not sure if it was a Sublime problem or a clash with another package. In any case, if I experience problems again I'll keep in mind the steps you provided.

Sorry for the noise, it should be safe to close this issue.
